server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # รองรับ React Router — ถ้าไม่เจอไฟล์ให้กลับไปที่ index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
